#!/usr/bin/env zsh
# {{VERSION}}-{{COMMIT}}
# SPDX-FileCopyrightText: © 2023-2026 David Parsons
# SPDX-License-Identifier: MIT

# Enable debug mode if DEBUG environment variable is set to any non-empty value
[[ -n "$DEBUG" ]] && set -x

# Provide custom colors in Terminal for status and error messages
msg_status() {
  echo "\033[0;32m$1\033[0m"
}

msg_warning() {
  echo "\033[0;33m$1\033[0m"
}

msg_error() {
  echo "\033[0;31m$1\033[0m"
}

msg_status "OC4VM VMware Disk Shrink"
msg_status "Writing temporary zero filled file"
msg_warning "Ignore any disk space errors"
mkfile 10g zerofile
sync
msg_status "Deleting temporary zero filled file"
rm ~/zerofile
sync
sleep 5
msg_warning "VMware disk shrinking started"
/Library/Application\ Support/VMware\ Tools/vmware-tools-daemon --cmd="disk.shrink"
msg_status "VMware disk shrinking completed"

exit 0
