#!/usr/bin/env zsh
# {{VERSION}}-{{COMMIT}}
# SPDX-FileCopyrightText: © 2023-25 David Parsons
# SPDX-License-Identifier: MIT

# Enable debug mode if DEBUG environment variable is set to any non-empty value
[[ -n "$DEBUG" ]] && set -x

# Define storage file location
DEFAULT_FILE="/Volumes/OPENCORE/EFI/OC/config.plist"
PLIST_FILE=${FILE:-$DEFAULT_FILE}

# Generate serial and MLB
input=$(${0:a:h}/macserial -m Macmini8,1 -n 1 `date +"-w %U -y %Y"`)
# Split into an array using the pipe as delimiter
parts=(${(s:|:)input})
# Trim whitespace from each part and assign to variables
serial=${parts[1]// /}
mlb=${parts[2]// /}

# Generate ROM
rom=$(xxd -l6 -p /dev/random | tr -d '\n' | tr '[:lower:]' '[:upper:]')

# Genenrate System UUID
uuid=$(uuidgen)

# Do the change
echo "OC4VM regen"
echo "-----------"
echo "Regenerating Mac identifiers..."
echo "Serial:  $serial"
echo "MLB:     $mlb"
echo "ROM:     $rom"
echo "UUID:    $uuid"
plutil -replace PlatformInfo.Generic.SystemSerialNumber -string ${serial} -- "${PLIST_FILE}"
plutil -replace PlatformInfo.Generic.MLB -string ${mlb} -- "${PLIST_FILE}"
plutil -replace PlatformInfo.Generic.ROM -string ${rom} -- "${PLIST_FILE}"
plutil -replace PlatformInfo.Generic.SystemUUID -string ${uuid} -- "${PLIST_FILE}"
